name: Reusable Validate

on:
  workflow_call:
    inputs:
      category:
        description: "HACS category"
        type: string
        default: "integration"

jobs:
  hassfest:
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: home-assistant/actions/hassfest@master

  hacs:
    name: HACS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hacs/action@main
        with:
          category: ${{ inputs.category }}
